# Generated by Django 3.2.8 on 2021-10-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FilePathField(),
        ),
    ]
