# Generated by Django 3.2.8 on 2021-10-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0003_alter_file_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='PDFFile',
        ),
    ]
