# Generated by Django 3.2.8 on 2021-10-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0005_auto_20211026_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='summary',
            field=models.CharField(max_length=50000),
        ),
    ]
