# Generated by Django 3.2.8 on 2021-11-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0006_alter_pdffile_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='summary',
            field=models.CharField(max_length=5000000),
        ),
    ]
